"""add collection and activity tables

Revision ID: 17e3e4e0213e
Revises: d1a275687c42
Create Date: 2026-09-18 23:12:49.868024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '17e3e4e0213e'
down_revision: Union[str, Sequence[str], None] = 'd1a275687c42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_messages'))
    )
    op.create_index('ix_chat_messages_session_id_created_at', 'chat_messages', ['session_id', 'created_at'], unique=False)
    op.create_table('collection_batches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('trigger', sa.String(length=16), nullable=False),
    sa.Column('operator_user_id', sa.UUID(), nullable=True),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('fetched_count', sa.Integer(), nullable=False),
    sa.Column('new_count', sa.Integer(), nullable=False),
    sa.Column('skipped_count', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['operator_user_id'], ['users.id'], name=op.f('fk_collection_batches_operator_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_collection_batches'))
    )
    op.create_table('learning_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('card_id', sa.String(length=64), nullable=True),
    sa.Column('topic', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('core_concepts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('time_budget_minutes', sa.Integer(), nullable=False),
    sa.Column('preferred_depth', sa.String(length=16), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('quiz_score', sa.Float(), nullable=True),
    sa.Column('fsrs_rating', sa.Integer(), nullable=True),
    sa.Column('fsrs_next_review_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_learning_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_learning_sessions')),
    sa.UniqueConstraint('session_id', name=op.f('uq_learning_sessions_session_id'))
    )
    op.create_index(op.f('ix_learning_sessions_user_id'), 'learning_sessions', ['user_id'], unique=False)
    op.create_table('user_activities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action_type', sa.String(length=32), nullable=False),
    sa.Column('target_type', sa.String(length=32), nullable=True),
    sa.Column('target_id', sa.String(length=64), nullable=True),
    sa.Column('request_id', sa.String(length=36), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_activities_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_activities'))
    )
    op.create_index(op.f('ix_user_activities_action_type'), 'user_activities', ['action_type'], unique=False)
    op.create_index('ix_user_activities_user_id_created_at', 'user_activities', ['user_id', 'created_at'], unique=False)
    op.create_table('user_bookmarks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_bookmarks_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_bookmarks')),
    sa.UniqueConstraint('user_id', 'item_id', name='uq_user_bookmarks_user_id_item_id')
    )
    op.create_index(op.f('ix_user_bookmarks_user_id'), 'user_bookmarks', ['user_id'], unique=False)
    op.create_table('collection_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.String(length=64), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=True),
    sa.Column('source_platform', sa.String(length=64), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('raw_description', sa.Text(), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('summary_generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('card_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('backfilled', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['collection_batches.id'], name=op.f('fk_collection_records_batch_id_collection_batches'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_collection_records')),
    sa.UniqueConstraint('item_id', name=op.f('uq_collection_records_item_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('collection_records')
    op.drop_index(op.f('ix_user_bookmarks_user_id'), table_name='user_bookmarks')
    op.drop_table('user_bookmarks')
    op.drop_index('ix_user_activities_user_id_created_at', table_name='user_activities')
    op.drop_index(op.f('ix_user_activities_action_type'), table_name='user_activities')
    op.drop_table('user_activities')
    op.drop_index(op.f('ix_learning_sessions_user_id'), table_name='learning_sessions')
    op.drop_table('learning_sessions')
    op.drop_table('collection_batches')
    op.drop_index('ix_chat_messages_session_id_created_at', table_name='chat_messages')
    op.drop_table('chat_messages')
    # ### end Alembic commands ###
