"""add learning_sessions.quiz_questions

Revision ID: 44de2b701220
Revises: 882bb8f3b226
Create Date: 2026-09-18 23:30:32.472909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '44de2b701220'
down_revision: Union[str, Sequence[str], None] = '882bb8f3b226'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('learning_sessions', sa.Column('quiz_questions', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('learning_sessions', 'quiz_questions')
    # ### end Alembic commands ###
