"""widen user_activities.request_id

Revision ID: 882bb8f3b226
Revises: 17e3e4e0213e
Create Date: 2026-09-18 23:22:10.476751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '882bb8f3b226'
down_revision: Union[str, Sequence[str], None] = '17e3e4e0213e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_activities', 'request_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=64),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_activities', 'request_id',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=36),
               existing_nullable=True)
    # ### end Alembic commands ###
